# Generated by Django 5.2.1 on 2025-05-23 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0001_initial"),
        ("order", "0003_alter_purchaseorder_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employee.employee",
            ),
        ),
    ]
