# Generated by Django 5.1.6 on 2025-05-28 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_remove_product_description_and_more"),
        ("supplier", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="supplier.supplier",
            ),
        ),
    ]
