# Generated by Django 5.2.1 on 2025-05-22 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0001_initial"),
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warehouse",
            name="manager",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="warehouses_managed",
                to="employee.employee",
            ),
        ),
    ]
