# Generated by Django 5.2.1 on 2025-05-20 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zone", models.CharField(max_length=50)),
                ("aisle", models.CharField(max_length=50)),
                ("rack", models.CharField(max_length=50)),
                ("bin", models.CharField(max_length=50)),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="warehouse.warehouse",
                    ),
                ),
            ],
            options={
                "unique_together": {("warehouse", "zone", "aisle", "rack", "bin")},
            },
        ),
    ]
