# Generated by Django 5.2.1 on 2025-05-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=64)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("boss", "Boss"),
                            ("tailor", "Tailor"),
                            ("reaper", "Reaper"),
                            ("manager", "Manager"),
                            ("chef", "Chef"),
                            ("cleaner", "Cleaner"),
                            ("other", "Other"),
                        ],
                        max_length=12,
                    ),
                ),
            ],
        ),
    ]
