# Generated by Django 5.2.1 on 2025-05-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="password",
            field=models.CharField(default="0111", max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="phone",
            field=models.CharField(default="+998949310666", max_length=13, unique=True),
            preserve_default=False,
        ),
    ]
